Домашнее задание 2: библиотека Numpy и линейная алгебра

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import ndimage  # спецификатор для работы с изображениями
from scipy import misc
import scipy.stats as sps

from PIL import Image

from random import randint

%matplotlib inline

Что такое NumPy? - это питоновская библиотека для работы с массивами 
Зачем используется и почему работает быстрее? - сам по себе питон не адаптирован к простой работе с массивами, а она адаптирована 
Что такое линейная алгебра? - это раздел математики, в котором оперируют матрицами
Как она связана с машинным обучением и глубоким обучением? - в машинном обучении мы будем оперировать матрицами

Задание 1

В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((10,10))
b = np.random.sample((10,10)) 
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
print(a.ndim)
print(b.ndim)
# Используйте функцию shape, что она вывела?
print(a.shape) # shape даёт число элементов по каждому из направлений матрицы
print(b.shape)
# ========
# тут можно писать код

def sc_matrix(matrix_first, matrix_second):
    ''' функция скалярного перемножения 2 матриц без np '''
    b = len(matrix_first[0]) != len(matrix_second)
    if b:
        return print('оу оу оу, такие матрицы перемножать скалярно не выйдет, число столбцов первой матрицы не равно числу строк второй')
    else:
        result_matrix = [[0 for el in range(0, len(matrix_second[0]))] for le in range(0, len(matrix_first))]
        for i in range(0, len(matrix_first)):
            for j in range(0, len(matrix_second[0])):
                for r in range(0, len(matrix_first[0])):
                    result_matrix[i][j] += matrix_first[i][r]*matrix_second[r][j]
        return np.array(result_matrix)

def sc_matrix_np(matrix_first, matrix_second):
    ''' функция скалярного перемножения 2 матриц с np '''
    try:
        return np.dot(matrix_first, matrix_second)
    except ValueError as ve:
        return print(f'ошибка: {ve}')

# ========
print(f'{a}\n')
print(b)

In [ ]:
%%timeit
# засечем время работы функции без NumPy
sc_matrix(a,b)

In [ ]:
%%timeit
# засечем время работы функции с NumPy
sc_matrix_np(a,b)

Разница $10^3$ нумпай впереди


Задание 2

Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$. Аналогично -- с помощью библиотеки NumPy и без нее. Сравните скорость, объясните результат.

In [9]:
n = int(input('Enter n, число элементов последовательности : '))
#a_list = np.random.sample((n,1))
#print(a_list)
# без библиотеки нумпай
a_list_sec = [randint(0, 10) for i in range(0, n)] # sps.uniform.rvs(size=10 ** 7) #
A = a_list_sec
#print(a_list_sec)
#print(a_list_sec.ndim)
#print(a_list_sec.shape)
#print(a_list_sec.size)
def wo_np_list(a_list_sec):
    ''' функция считает последовательность без юзания нумпая '''
    # print(f'исходный вектор : {a_list_sec}')
    a_sum = 0
    s_list = [0 for i in range(0, len(a_list_sec))]
    for i, j in enumerate(a_list_sec):
        a_sum += j
        s_list[i] = round(a_sum / (i+1), 2)
    return s_list # f'конечная последовательность : {s_list}'

#s_list = wo_np_list(a_list_sec)
#print(s_list)

# с библиотекой нумпай
def w_np_list(a_list):
    ''' функция считает последовательность с юзанием нумпая '''
    a_list_sec = np.array(a_list)
    # print(f'исходный вектор : {a_list_sec}')
    a_list_test = np.array([round(a_list_sec[:i].sum()/(i),2) for i in range(1, n+1)])
    return a_list_test # f'конечная последовательность : {a_list_test}'

#s_list = w_np_list(a_list_sec)
#print(s_list)

Enter n, число элементов последовательности : 3


In [22]:
%timeit S1 = wo_np_list(A)
%timeit S2 = w_np_list(A)
S1 = wo_np_list(A)
S2 = w_np_list(A)
#проверим корректность:
np.abs(S1 - S2).sum()

3.53 µs ± 250 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
31.5 µs ± 3.39 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


0.0

Задание 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить массив $X$ с преобразованным $X$ и вывести в обратном порядке.

In [9]:
x_list = [randint(-10, 10) for i in range(0, randint(0, 50))]
def wo_np_list(x_list, a = 1):
    ''' без нумпая делаем всё что нужно '''
    xx_list_rev = x_list[::-1]
    xx_list = [a if i%2 == 0 else xx_list_rev[len(x_list) - i]**3 for i in range(0, len(x_list))]
    return (x_list + xx_list)[::-1]
print(wo_np_list(x_list))

#def wo_np_list_sec(x_list, a = 1):
#    ''' без нумпая делаем всё что нужно. не через генератор '''
#    xx_list_rev = x_list[::-1]
#    xx_list = [a if i%2 == 0 else xx_list_rev[i]**3 for i in range(0, len(x_list))]
#    return (x_list + xx_list)[::-1]

def w_np_list(x_list, a = 1):
    ''' с нумпаем делаем всё что нужно '''
    x_list_second = np.array(x_list)
    x_list = np.array(x_list)
    x_list_one[::4] = a / (x_list**3) 
    x_list_rev =  x_list[::-1] * 
    
    


SyntaxError: invalid syntax (<ipython-input-9-17790c8067b8>, line 20)

In [14]:
x_list = [2 for i in range(0, randint(0, 10))] #randint(1, 10)
x_list_second = np.array(x_list)
print(x_list_second)
print(len(x_list))
x_list = np.array(x_list)
i = 0
for i in range(0, len(x_list)):
    if i % 2 == 0:
        x_list_second[i] = 1
    else: 
        x_list_second[i] = x_list_second[len(x_list) - i]**3
print(x_list_second)
print(x_list.ndim)
matrix_result = np.concatenate((x_list,x_list_second),axis=0)  

[2 2 2]
3
[1 8 1]
1


Задание 4

Вам подаются на вход два вектора a и b в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy и без. Засеките время работы, как это показано в заданиях выше.

In [55]:
a_matrix = [randint(0, 1000) for i in range(0, 3)]# [1,2,3] #np.random.randint(0, 10, (3)) 
b_matrix = [randint(0, 1000) for i in range(0, 3)]# [1,2,3] #np.random.randint(0, 10, (3)).transpose()
print(a_matrix)
print(b_matrix)

def sc_matrix_np(matrix_first, matrix_second):
    ''' функция скалярного перемножения 2 матриц с np'''
    matrix_first = np.array(matrix_first)
    matrix_second = np.array(matrix_second).transpose()
    try:
        return np.dot(matrix_first, matrix_second) # перемножаем норм на транспонированную
    except ValueError as ve:
        return print(f'ошибка: {ve}')
print(sc_matrix_np(a_matrix, b_matrix))


def sc_matrix(matrix_first, matrix_second):
    ''' функция скалярного перемножения 2 матриц без np '''
    b = len(matrix_first) != len(matrix_second)
    if b:
        return print('оу оу оу, такие матрицы перемножать скалярно не выйдет, число столбцов первой матрицы не равно числу строк второй')
    else:
        result_matrix = [0 for el in range(0, len(matrix_second))]
        for i in range(0, len(matrix_first)):
            result_matrix[i] += matrix_first[i]*matrix_second[i]
        return sum(result_matrix)
# a_matrix = [1,2,3] #[randint(0, 10) for i in range(0, 3)]
# b_matrix = [1,2,3] #[randint(0, 10) for i in range(0, 3)]
print(a_matrix)
print(b_matrix)
print(sc_matrix(a_matrix, b_matrix))

[297, 741, 616]
[400, 708, 187]
758620
[297, 741, 616]
[400, 708, 187]
758620


In [57]:
%timeit product_1 = sc_matrix_np(a_matrix, b_matrix)
%timeit product_2 = sc_matrix(a_matrix, b_matrix)
# проверим корректность:
np.abs(product_1 - product_2).sum()

8.89 µs ± 398 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.37 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


0

Задание 5*

Нужно написать матричное произведение БЕЗ циклов и БЕЗ символа @, БЕЗ np.dot 
и вообще БЕЗ какой-либо вспомогательной функции из numpy, то есть пользуясь только 
индексированием, взятем суммы по нужным осям и поэлементным произведенем (да, это возможно). 
Рекомендуем гуглить по запросу "NumPy broadcasting"

In [62]:
a_matrix = np.random.randint(0, 10, (3, 3)) 
b_matrix = np.random.randint(0, 10, (3, 3)) 
print(a_matrix)
print(b_matrix)

def sc_matrix(first_matrix, second_matrix):
    ''' скалярное произведение двух матриц без рук '''
    ''' силами индексирования, суммы и поэлементного произведения '''
    return np.sum(first_matrix.T*second_matrix,axis=0)

print(a_matrix * b_matrix)
a_matrix[0][0]*b_matrix[0][0] + a_matrix[0][1]*b_matrix[1][0] + a_matrix[0][2]*b_matrix[2][0]

    

[[9 1 8]
 [6 3 2]
 [1 2 7]]
[[9 9 9]
 [1 2 5]
 [1 2 7]]
[[81  9 72]
 [ 9  2 40]
 [ 9  2 56]]
