In [10]:
#в качестве примера
import numpy as np
x = [[[5,9,7],[3, 4, 1]],[[5,9,7],[3, 4, 1]]]
a = np.array(x)
d = a.ndim # число измерений массива
s = a.shape # длина массива по каждой оси
sz = a.size # число элементов массива
print(a)
print(d)
print(s)
print(sz)


[[[5 9 7]
  [3 4 1]]

 [[5 9 7]
  [3 4 1]]]
3
(2, 2, 3)
12
