Упражнение 3

Перемножьте векторы поэлементно и скалярно:

1). (1,2,3) и (10, 100, -4)

2). (0, -5, 0.5) и (2, -2.3, 11)

3). (1, 1, 1, 1, 1, 1) и (2, -2, -3, -100, 33, 0.55)

4). (5, 2) и (1, 2, 3)


In [ ]:
# Решение: зачем это решать на листике бумажки, если можно запрогать)) чтобы было интереснее, перемножаем сразу в python
dim_matrix = int(input('сколько элементов в одномерной матрице? : '))
matrix_first = []
matrix_second = []
matrix_el_summ = []
matrix_sc_summ = 0
for i in range(0, dim_matrix):
    matrix_first.append(float(input(f'введите {i+1}-й элемент первой одномерной матрицы')))
for i in range(0, dim_matrix):
    matrix_second.append(float(input(f'введите {i+1}-й элемент второй одномерной матрицы')))
    matrix_el_summ.append(matrix_first[i]*matrix_second[i])
for i in range(0, dim_matrix):
    matrix_sc_summ += matrix_second[i]*matrix_first[i]
print(f'Поэлементное перемножение векторов {matrix_first} и {matrix_second} даёт {matrix_el_summ}')
print(f'Скалярное произведение векторов {matrix_first} и {matrix_second} даёт {matrix_sc_summ}')

Упражнение 4

Поделите векторы из пункта 3 предыдущего упражнения.


In [ ]:
# Решение: зачем это решать на листике бумажки, если можно запрогать)) чтобы было интереснее, перемножаем сразу в python
dim_matrix = int(input('сколько элементов в одномерной матрице? : '))
matrix_first = []
matrix_second = []
matrix_el_summ = []
for i in range(0, dim_matrix):
    matrix_first.append(float(input(f'введите {i+1}-й элемент первой одномерной матрицы')))
for i in range(0, dim_matrix):
    matrix_second.append(float(input(f'введите {i+1}-й элемент второй одномерной матрицы')))
    matrix_el_summ.append(matrix_first[i]/matrix_second[i])
print(f'Поэлементное деление векторов {matrix_first} и {matrix_second} даёт {matrix_el_summ}')


Упражнение 5

Сложите, вычтите, поэлементно умножьте и поделите матрицы:

\begin{pmatrix}
  1 & 2 & 10\\
  5 & 1 & -13\\
\end{pmatrix}
и 
\begin{pmatrix}
 -5 & -5 & 3\\
  0 & 1 & 2\\
\end{pmatrix}

In [ ]:
#решение: сделаем круче, пусть элементы матриц будут ранумными,
#а размер матриц мы задаём с самого начала сами
from random import randint
import numpy as np

def int_h_l_matrix(name_obj, num_mtrx):
    while True:
        try:
            result = int(input(f'введите число {name_obj} матрицы {num_mtrx} : '))
            return result
            break
        except ValueError as VE:
            print(f'ненене, введи целые числа, а то ошибка : {VE}')

def summ_matrix(matrix_first, matrix_second):
    ''' сложение 2 матриц '''
    summ_matrix = [[0 for el in range(0, len(matrix_first[0]))] for le in range(0, len(matrix_first))]
    for i in range(0, len(matrix_first)):
        for j in range(0, len(matrix_first[0])):
            summ_matrix[i][j] = matrix_first[i][j] + matrix_second[i][j]
    return summ_matrix
    
def diff_matrix(matrix_first, matrix_second):
    ''' разница 2 матриц '''
    diff_matrix = [[0 for el in range(0, len(matrix_first[0]))] for le in range(0, len(matrix_first))]
    diff_matrix = np.array(matrix_second) + np.array(matrix_first)
    return diff_matrix
    
def mpc_matrix(matrix_first, matrix_second):
    ''' перемножение 2 матриц '''
    mpc_matrix = [[0 for el in range(0, len(matrix_first[0]))] for le in range(0, len(matrix_first))]
    for i in range(0, len(matrix_first)):
        for j in range(0, len(matrix_first[0])):
            mpc_matrix[i][j] = matrix_first[i][j] * matrix_second[i][j]
    return mpc_matrix    

def cpm_matrix(matrix_first, matrix_second):
    ''' переделение 2 матриц '''
    cpm_matrix = [[0 for el in range(0, len(matrix_first[0]))] for le in range(0, len(matrix_first))]
    for i in range(0, len(matrix_first)):
        for j in range(0, len(matrix_first[0])):
            cpm_matrix[i][j] = matrix_first[i][j] / matrix_second[i][j]
            cpm_matrix[i][j] = round(cpm_matrix[i][j], 2)
    return cpm_matrix 
            
while True:
    h_matrix_first = int_h_l_matrix('строк', '1')
    l_matrix_first =  int_h_l_matrix('столбцов', '1')
    h_matrix_second = int_h_l_matrix('строк', '2')
    l_matrix_second = int_h_l_matrix('столбцов', '2')
    if h_matrix_first != h_matrix_second and l_matrix_first != l_matrix_second:
        print('оу оу оу, к нам с такими матрицами нельзя, давай вводи всё заново')
    else:
        matrix_first = [[randint(1, 10) for el in range(0, l_matrix_first)] for le in range(0, h_matrix_first)]
        matrix_second = [[randint(1, 10) for el in range(0, l_matrix_second)] for le in range(0, h_matrix_second)]
        print(f'\nот такая матрица номер 1:\n{np.array(matrix_first)}')
        print(f'вот такая матрица номер 2:\n{np.array(matrix_second)}')
        print(f'результат сложения:\n{np.array(summ_matrix(matrix_first, matrix_second))}')
        print(f'результат вычитания:\n{diff_matrix(matrix_second, matrix_first)}')
        print(f'результат поэлементного перемножения:\n{np.array(mpc_matrix(matrix_first, matrix_second))}')
        print(f'результат поэлементного деления:\n{np.array(cpm_matrix(matrix_first, matrix_second))}')
        break
        


Упражнение 6
Перемножьте матрицы (матрично) (они умышленно даны в таком виде -- нужно привыкать):

a):
A = [[2, 3, -2], [9, 0, 1], [1, 0, 0]]
B = [[1], [2], [3]]

b):
A = [[10, 20, 30, 5], [-9, -1, 2, -1]]
B = [[1, 1], [2, 2], [5, 5], [11, 12]]

c): A = [[10, 20, 30, 5], [-9, -1, 2, -1]]
B = [[1, 1], [2, 2], [5, 5]]

In [14]:
# я хочу еделать в 2 видах. в 1, когда я сам напишу цикольное перемножение
# и 2 - это уже через np
from random import randint
import numpy as np

#сложный вывод: если без нумпая, то мы пишем функцию перемножения
def sc_matrix(matrix_first, matrix_second):
    ''' функция скалярного перемножения 2 матриц '''
    b = len(matrix_first[0]) != len(matrix_second)
    if b:
        return print('оу оу оу, такие матрицы перемножать скалярно не выйдет, число столбцов первой матрицы не равно числу строк второй')
    else:
        result_matrix = [[0 for el in range(0, len(matrix_second[0]))] for le in range(0, len(matrix_first))]
        for i in range(0, len(matrix_first)):
            for j in range(0, len(matrix_second[0])):
                for r in range(0, len(matrix_first[0])):
                    result_matrix[i][j] += matrix_first[i][r]*matrix_second[r][j]
        return result_matrix

# сделаем здесь обработку ошибки, может быть нам это понадобится
def sc_matrix_np(matrix_first, matrix_second):
    try:
        return np.dot(matrix_first, matrix_second)
    except ValueError as ve:
        return print(f'ошибка: {ve}')
        
        
a_matrix = [[2, 3, -2], [9, 0, 1], [1, 0, 0]]
b_matrix = [[1], [2], [3]]
print(f'\nот такая матрица номер 1:\n{np.array(a_matrix)}')
print(f'вот такая матрица номер 2:\n{np.array(b_matrix)}')
print(f'вот такой сложный вывод скалярного произведения:\n{np.array(sc_matrix(a_matrix, b_matrix))}')
print(f'вот такой простой вывод скалярного произведения матриц:\n{np.dot(a_matrix,b_matrix)}')

print('\nВариант b)')
a_matrix = [[10, 20, 30, 5], [-9, -1, 2, -1]] 
b_matrix = [[1, 1], [2, 2], [5, 5], [11, 12]]
print(f'\nот такая матрица номер 1:\n{np.array(a_matrix)}')
print(f'вот такая матрица номер 2:\n{np.array(b_matrix)}')
print(f'вот такой сложный вывод скалярного произведения:\n{np.array(sc_matrix(a_matrix, b_matrix))}')
print(f'вот такой простой вывод скалярного произведения матриц:\n{np.dot(a_matrix,b_matrix)}')

print('\nВариант c)')
a_matrix = [[10, 20, 30, 5], [-9, -1, 2, -1]] 
b_matrix = [[1, 1], [2, 2], [5, 5]]
print(f'\nот такая матрица номер 1:\n{np.array(a_matrix)}')
print(f'вот такая матрица номер 2:\n{np.array(b_matrix)}')
print(f'вот такой сложный вывод скалярного произведения:\n{np.array(sc_matrix(a_matrix, b_matrix))}')
print(f'вот такой простой вывод скалярного произведения матриц:\n{sc_matrix_np(a_matrix,b_matrix)}')






от такая матрица номер 1:
[[ 2  3 -2]
 [ 9  0  1]
 [ 1  0  0]]
вот такая матрица номер 2:
[[1]
 [2]
 [3]]
вот такой сложный вывод скалярного произведения:
[[ 2]
 [12]
 [ 1]]
вот такой простой вывод скалярного произведения матриц:
[[ 2]
 [12]
 [ 1]]

Вариант b)

от такая матрица номер 1:
[[10 20 30  5]
 [-9 -1  2 -1]]
вот такая матрица номер 2:
[[ 1  1]
 [ 2  2]
 [ 5  5]
 [11 12]]
вот такой сложный вывод скалярного произведения:
[[255 260]
 [-12 -13]]
вот такой простой вывод скалярного произведения матриц:
[[255 260]
 [-12 -13]]

Вариант c)

от такая матрица номер 1:
[[10 20 30  5]
 [-9 -1  2 -1]]
вот такая матрица номер 2:
[[1 1]
 [2 2]
 [5 5]]
оу оу оу, такие матрицы перемножать скалярно не выйдет, число столбцов первой матрицы не равно числу строк второй
вот такой сложный вывод скалярного произведения:
None
ошибка: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)
вот такой простой вывод скалярного произведения матриц:
None
